name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn mlflow
          
      - name: Menjalankan Script Pelatihan Model
        run: |
          cd MLProject
          # Menambahkan flag --no-conda agar tidak mencari Conda sama sekali
          mlflow run . --no-conda